// §31 — Event name constants + factory helpers
import { EventName } from "./base-event";

export const EVENT_NAMES: Readonly<Record<EventName, EventName>> = {
  CapacityUnitStatusChanged: "CapacityUnitStatusChanged",
  InventoryVerified: "InventoryVerified",
  InventoryRevoked: "InventoryRevoked",
  TokenOffered: "TokenOffered",
  TokenAccepted: "TokenAccepted",
  TokenHeld: "TokenHeld",
  TokenActivated: "TokenActivated",
  TokenFulfilled: "TokenFulfilled",
  TokenDowngraded: "TokenDowngraded",
  TokenForfeited: "TokenForfeited",
  TokenRefunded: "TokenRefunded",
  TokenVoidedByEmergency: "TokenVoidedByEmergency",
  FulfillmentVerified: "FulfillmentVerified",
  DisputeOpened: "DisputeOpened",
  DisputeResolved: "DisputeResolved",
  EscrowTopUp: "EscrowTopUp",
  EscrowDrawDown: "EscrowDrawDown",
  OverrideGranted: "OverrideGranted",
  OverrideExpired: "OverrideExpired",
  SafetyConstraintBlocked: "SafetyConstraintBlocked",
  ProviderFailureAdjudicated: "ProviderFailureAdjudicated",
  OperatingModeChanged: "OperatingModeChanged",
  PlanCommitted: "PlanCommitted",
  SourceIngested: "SourceIngested",
  SourceTrustChanged: "SourceTrustChanged",
  UnsafeZoneChanged: "UnsafeZoneChanged",
  SpikeDetected: "SpikeDetected",
  DataConflict: "DataConflict",
  AnomalyDetected: "AnomalyDetected",
  ForecastEmitted: "ForecastEmitted",
  ForecastInvalidated: "ForecastInvalidated",
  BaselineUpdated: "BaselineUpdated",
};
